### ISSUE TITLE
Warning issue for the model

### ISSUE THREAD

**Issue by suraj1222** [kulkarni-harsh/signature-verification-tool#2]
The warnings we get when we run the model or while checking evaluation of the model are occurring as an issue while running the streamlit app
So I am getting all the images loaded as forged only

**Comment by kulkarni-harsh** [comment]
Hi Suraj,
I looked into the application and found out that my GitHub Large File System plan was exhausted. 
I have changed the code so now the model is downloaded from Google Drive using gdown library before the app starts running and now it works fine locally as well as on Streamlit (which had errors due to GitHub LFS).
